workflows:
  my-workflow:
    name: fees workflows
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    max_build_duration: 30
    inputs: # more information about build inputs:https://docs.codemagic.io/knowledge-codemagic/build-inputs/
      name: # input ID
        description: Beginning deployment to Google playStore
        default: Codemagic
    environment:
      groups:
        - google_credentials
      flutter: stable
    triggering:
      events:
        - tag
      cancel_previous_builds: true
    scripts:
    - name: Setup the keystore
      script: |
        echo $KEYSTORE_FILE | base64 --decode > /tmp/fees.jks
        cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
        storePassword=$KEYSTORE_PASSWORD
        keyPassword=$KEYSTORE_KEY_PASSWORD
        keyAlias=fees_deployment
        storeFile=/tmp/fees.jks
        EOF
    - name: Build AAB
      script: |
        cd $CM_BUILD_DIR
        flutter packages pub get
        flutter build appbundle
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/apk/**/*.apk  
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: alpha
      scripts:
        - echo 'Succeffuly publish to playStore'

