// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC89OPWceedb0M8wX0-LS8gjWGLsN8v74A',
    appId: '1:425516267215:web:e34c93e16b1e8af3ac69ba',
    messagingSenderId: '425516267215',
    projectId: 'fess-428518',
    authDomain: 'fess-428518.firebaseapp.com',
    storageBucket: 'fess-428518.appspot.com',
    measurementId: 'G-3VB0YSZ3TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyePUGy5mkLO03L-hOWggUvt_oZFyZEs',
    appId: '1:425516267215:android:dd553d8c9aae930aac69ba',
    messagingSenderId: '425516267215',
    projectId: 'fess-428518',
    storageBucket: 'fess-428518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_htM2geo9k5-_bTuEGJ3832AtezQsGQ',
    appId: '1:425516267215:ios:902c9abcfbf72408ac69ba',
    messagingSenderId: '425516267215',
    projectId: 'fess-428518',
    storageBucket: 'fess-428518.appspot.com',
    iosClientId: '425516267215-lle4o93dqfofuknurnfvop54bd8luapd.apps.googleusercontent.com',
    iosBundleId: 'com.fees.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_htM2geo9k5-_bTuEGJ3832AtezQsGQ',
    appId: '1:425516267215:ios:c11946a38ce48727ac69ba',
    messagingSenderId: '425516267215',
    projectId: 'fess-428518',
    storageBucket: 'fess-428518.appspot.com',
    iosClientId: '425516267215-ftg81frhbqvu97um5al6lk971tuhqcv7.apps.googleusercontent.com',
    iosBundleId: 'com.fees.crytoWallet3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC89OPWceedb0M8wX0-LS8gjWGLsN8v74A',
    appId: '1:425516267215:web:0c7e7291fd83fff2ac69ba',
    messagingSenderId: '425516267215',
    projectId: 'fess-428518',
    authDomain: 'fess-428518.firebaseapp.com',
    storageBucket: 'fess-428518.appspot.com',
    measurementId: 'G-H92VZ797SR',
  );
}
